[window]
opacity = 0.85

[colors.bright]
black = "0x282a40"
blue = "0xa3c5ff"
cyan = "0x98fffd"
green = "0xe0ffad"
magenta = "0xd6afed"
red = "0xeb7f84"
white = "0xd1e5ed"
yellow = "0xffee7e"

[colors.normal]
black = "0x181a29"
blue = "0x93bbff"
cyan = "0x98e4ff"
green = "0xcdea9f"
magenta = "0xd3a7ee"
red = "0xF07178"
white = "0xbfd5de"
yellow = "0xffd47e"

[colors.primary]
background = "0x212121"
foreground = "0xc5c9de"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 3
y = 2
